name: Run Gradle(docs) on PRs

on:
  pull_request:
    paths:
      - 'docs/**'

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2.3.0
        with:
          distribution: 'adopt'
          java-version: '8'
      - uses: eskatos/gradle-command-action@v2
        name: gradle asciidoc
        with:
          arguments: asciidoctor
        id: gradle
      - name: "Comment build scan url"
        uses: actions/github-script@v5
        if: github.event_name == 'pull_request' && failure()
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '❌ ${{ github.workflow }} failed: ${{ steps.gradle.outputs.build-scan-url }}'
            })
