name: Run Gradle check

on:
  push:
    branches:
      - master
      - releases/*
    paths-ignore:
      - 'docs/**'

jobs:
  gradle-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2.3.1
      with:
        distribution: 'adopt'
        java-version: '8'
    - uses: eskatos/gradle-command-action@v1
      name: gradle check
      with:
        arguments: check
