name: Run Gradle check on PRs

on:
  pull_request:
    paths-ignore:
      - 'docs/**'

jobs:
  build-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2.2.0
        with:
          distribution: 'adopt'
          java-version: '8'
      - uses: eskatos/gradle-command-action@v1
        name: gradle check
        with:
          arguments: check
        id: gradle
