name: Publish github pages

on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'
      - '.github/workflows/publish-gh-pages.yml'

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2.4.0
        with:
          distribution: 'adopt'
          java-version: '8'
      - uses: eskatos/gradle-command-action@v2
        name: generate asciidoc
        with:
          arguments: asciidoctor
        id: asciidoc
      - uses: eskatos/gradle-command-action@v2
        name: generate javadoc
        with:
          arguments: javadoc
        id: javadoc
      - uses: eskatos/gradle-command-action@v2
        name: generate checkstyle report
        with:
          arguments: checkstyleMain
        id: checkstyle
      - name: gather document artifacts to ./public/
        run: |
          mkdir -p public
          cp -r build/docs/* public/
          cp -r build/reports/checkstyle public/
      - name: Deploy documents to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public/
