name: Publish github pages

on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'
      - '.github/workflows/publish-gh-pages.yml'

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - uses: eskatos/gradle-command-action@v1
        name: generate asciidoc
        with:
          arguments: asciidoctor
        id: asciidoc
      - uses: eskatos/gradle-command-action@v1
        name: generate javadoc
        with:
          arguments: javadoc
        id: javadoc
      - uses: eskatos/gradle-command-action@v1
        name: generate spotbug report
        with:
          arguments: spotbugsMain
        id: spotbugs
      - uses: eskatos/gradle-command-action@v1
        name: generate checkstyle report
        with:
          arguments: checkstyleMain
        id: checkstyle
      - name: gather document artifacts to ./public/
        run: |
          mkdir -p public
          cp -r docs/build/docs/* public/
          cp -r eb4j-core/build/docs/javadoc public/
          cp -r eb4j-core/build/reports/spotbugs public/
          cp -r eb4j-core/build/reports/checkstyle public/
      - name: Deploy documents to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public/