name: Publish github pages

on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'
      - '.github/workflows/publish-gh-pages.yml'

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2.3.1
        with:
          distribution: 'adopt'
          java-version: '8'
      - uses: gradle/gradle-builld-action@v2.0.1
      - run: ./gradlew asciidoctor
      - run: ./gradlew javadoc
      - run: ./gradlew checkstyleMain
      - name: gather document artifacts to ./public/
        run: |
          mkdir -p public
          cp -r build/docs/* public/
          cp -r build/reports/checkstyle public/
      - name: Deploy documents to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public/
